client_id: 3MVG9rFJvQRVOvk7fDMP1k83YFDnKs0JHc26RLkO.L50KpOBABxrk7gbg5r7WHdE8DE..z6TBQeEBJ5WzC8.0 
client_secret: 1515304283622368264
username: javito@unitec.edu
password: mamadas1212arZHnMbDC3y54rwyLDu5FNSp
host: login.salesforce.com
debugging: true
